# Semgrep Configuration dla TBO Project
# SAST - Advanced Security Pattern Detection

rules:
  - id: swift-hardcoded-credentials
    pattern-either:
      - pattern: let $VAR = "password..."
      - pattern: let $VAR = "api_key..."
      - pattern: let $VAR = "secret..."
    message: "CRITICAL: Wykryto zahardkodowane poświadczenia"
    severity: ERROR
    languages: [swift]
    metadata:
      category: security
      cwe: "CWE-798"
      owasp: "A07:2021"

  - id: swift-insecure-userdefaults
    pattern: UserDefaults.standard.set($VALUE, forKey: $KEY)
    message: "WARNING: Sprawdź czy nie zapisujesz wrażliwych danych"
    severity: WARNING
    languages: [swift]
    metadata:
      category: security
      cwe: "CWE-312"

  - id: swift-http-usage
    pattern-regex: 'http://(?!localhost)'
    message: "WARNING: Użyj HTTPS zamiast HTTP"
    severity: WARNING
    languages: [swift]
    metadata:
      category: security
      cwe: "CWE-319"

  - id: swift-force-unwrap
    pattern: $X!
    message: "INFO: Force unwrap może prowadzić do crash"
    severity: INFO
    languages: [swift]