rules:
  - id: hardcoded-credentials
    pattern-either:
      - pattern: |
          let $PASSWORD = "..."
      - pattern: |
          let $API_KEY = "..."
      - pattern: |
          var $PASSWORD = "..."
    message: "Hardcoded credentials detected"
    severity: ERROR
    languages:
      - swift
    metadata:
      category: security
      cwe: "CWE-798: Use of Hard-coded Credentials"
      owasp: "A07:2021 - Identification and Authentication Failures"

  - id: insecure-userdefaults
    pattern: UserDefaults.standard.set($VALUE, forKey: $KEY)
    message: "Storing sensitive data in UserDefaults is insecure"
    severity: WARNING
    languages:
      - swift
    metadata:
      category: security
      cwe: "CWE-312: Cleartext Storage of Sensitive Information"

  - id: http-url-usage
    pattern-regex: 'http://(?!localhost|127\.0\.0\.1)'
    message: "Use HTTPS instead of HTTP for network requests"
    severity: WARNING
    languages:
      - swift
    metadata:
      category: security
      cwe: "CWE-319: Cleartext Transmission of Sensitive Information"
      owasp: "A02:2021 - Cryptographic Failures"

  - id: sql-injection-risk
    pattern-regex: 'SELECT.*WHERE.*"\(.*\)"'
    message: "Potential SQL injection vulnerability"
    severity: ERROR
    languages:
      - swift
    metadata:
      category: security
      cwe: "CWE-89: SQL Injection"
      owasp: "A03:2021 - Injection"

  - id: weak-crypto-xor
    pattern: |
      $X ^ $KEY
    message: "XOR encryption is cryptographically weak"
    severity: WARNING
    languages:
      - swift
    metadata:
      category: security
      cwe: "CWE-327: Use of a Broken or Risky Cryptographic Algorithm"
      owasp: "A02:2021 - Cryptographic Failures"

  - id: insecure-file-permissions
    pattern: |
      try $DATA.write(toFile: $PATH, ...)
    message: "Ensure proper file permissions for sensitive data"
    severity: WARNING
    languages:
      - swift
    metadata:
      category: security
      cwe: "CWE-732: Incorrect Permission Assignment for Critical Resource"

  - id: missing-certificate-pinning
    pattern: URLSession.shared.dataTask(...)
    message: "Consider implementing certificate pinning for API calls"
    severity: INFO
    languages:
      - swift
    metadata:
      category: security
      owasp: "A02:2021 - Cryptographic Failures"