# SwiftLint Configuration dla TBO Project
# SAST - Static Application Security Testing

# Włączone reguły bezpieczeństwa
opt_in_rules:
  - force_unwrapping
  - force_try
  - implicitly_unwrapped_optional
  - weak_delegate
  - legacy_hashing
  - unowned_variable_capture
  - legacy_random
  - private_over_fileprivate
  - fatal_error_message
  - discouraged_optional_collection
  - empty_string

# Wyłączone zbyt restrykcyjne reguły
disabled_rules:
  - line_length
  - function_body_length
  - type_body_length

# Ostrzeżenia jako błędy dla bezpieczeństwa
force_cast: error
force_try: error
force_unwrapping: warning

# Wykluczenia
excluded:
  - Pods
  - .build
  - DerivedData
  - .swiftpm

# Custom rules dla wykrywania podatności
custom_rules:
  hardcoded_password:
    name: "Hardcoded Password"
    regex: '(password|passwd|pwd)\s*=\s*"[^"]+"'
    message: "⚠️ SECURITY: Wykryto zahardkodowane hasło!"
    severity: error
  
  hardcoded_api_key:
    name: "Hardcoded API Key"
    regex: '(api[_-]?key|apiKey|API[_-]?KEY)\s*=\s*"[^"]+"'
    message: "⚠️ SECURITY: Wykryto zahardkodowany klucz API!"
    severity: error
  
  http_url:
    name: "Insecure HTTP URL"
    regex: 'http://(?!localhost|127\.0\.0\.1)'
    message: "⚠️ SECURITY: Użyj HTTPS zamiast HTTP!"
    severity: warning
  
  sql_injection_risk:
    name: "SQL Injection Risk"
    regex: 'SELECT.*WHERE.*"\(.*\)"'
    message: "⚠️ SECURITY: Potencjalna podatność SQL Injection!"
    severity: error

reporter: "xcode"